import goCodeeLogoFirst from "~assets/images/gocodee-logo-first.png";

import goCodeeBackgroundImage from "~assets/images/background/background-image-gocodee.jpg";

export const timelineListValue = [
  {
    id: "gocodee",
    companyName: "Gocodee",
    name: "Gocodee",
    link: "",
    position: "Web Developer, Mobile Developer",
    duration: "May 2018 - Now",
    location: "HCM City, Viet Nam",
    roleDetail: "",
    companyDetail: "",
    firstLogo: goCodeeLogoFirst,

    backgroundImage: goCodeeBackgroundImage,
    projects: ["Project1", "Project2", "Project3", "Project4", "Project5"],
  },
  {
    id: "gocodee2",
    companyName: "Gocodee12321",
    name: "Gocodee12321",
    link: "",
    position: "Web Developer, Mobile Developer",
    duration: "May 2018 - Now",
    location: "HCM City, Viet Nam",
    roleDetail: "",
    companyDetail: "",
    firstLogo: goCodeeLogoFirst,

    backgroundImage: goCodeeBackgroundImage,
    projects: ["Project1", "Project2"],
  },
  {
    id: "gocodee3",
    companyName: "Gocodee123123213",
    name: "Gocodee123123213",
    link: "",
    position: "Web Developer, Mobile Developer",
    duration: "May 2018 - Now",
    location: "HCM City, Viet Nam",
    roleDetail: "",
    companyDetail: "",
    firstLogo: goCodeeLogoFirst,

    backgroundImage: goCodeeBackgroundImage,
    projects: ["Project1"],
  },
  // {
  //   id: "gocodee354533",
  //   companyName: "Gocodee123123213",
  //   name: "Gocodee123123213",
  //   link: "",
  //   position: "Web Developer, Mobile Developer",
  //   duration: "May 2018 - Now",
  //   location: "HCM City, Viet Nam",
  //   roleDetail: "",
  //   companyDetail: "",
  //   firstLogo: goCodeeLogoFirst,

  //   backgroundImage: goCodeeBackgroundImage,
  //   projects: ["Project1", "Project2", "Project3", "Project4", "Project5"],
  // },
  // {
  //   id: "gocodee332",
  //   companyName: "Gocodee123123213",
  //   name: "Gocodee123123213",
  //   link: "",
  //   position: "Web Developer, Mobile Developer",
  //   duration: "May 2018 - Now",
  //   location: "HCM City, Viet Nam",
  //   roleDetail: "",
  //   companyDetail: "",
  //   firstLogo: goCodeeLogoFirst,

  //   backgroundImage: goCodeeBackgroundImage,
  //   projects: ["Project1", "Project2", "Project3", "Project4", "Project5"],
  // },
  // {
  //   id: "gocodee34",
  //   companyName: "Gocodee123123213",
  //   name: "Gocodee123123213",
  //   link: "",
  //   position: "Web Developer, Mobile Developer",
  //   duration: "May 2018 - Now",
  //   location: "HCM City, Viet Nam",
  //   roleDetail: "",
  //   companyDetail: "",
  //   firstLogo: goCodeeLogoFirst,

  //   backgroundImage: goCodeeBackgroundImage,
  //   projects: ["Project1", "Project2", "Project3", "Project4", "Project5"],
  // },
  // {
  //   id: "gocodee332432",
  //   companyName: "Gocodee123123213",
  //   name: "Gocodee123123213",
  //   link: "",
  //   position: "Web Developer, Mobile Developer",
  //   duration: "May 2018 - Now",
  //   location: "HCM City, Viet Nam",
  //   roleDetail: "",
  //   companyDetail: "",
  //   firstLogo: goCodeeLogoFirst,

  //   backgroundImage: goCodeeBackgroundImage,
  //   projects: ["Project1", "Project2", "Project3", "Project4", "Project5"],
  // },
  // {
  //   id: "gocodee123",
  //   companyName: "Gocodee123123213",
  //   name: "Gocodee123123213",
  //   link: "",
  //   position: "Web Developer, Mobile Developer",
  //   duration: "May 2018 - Now",
  //   location: "HCM City, Viet Nam",
  //   roleDetail: "",
  //   companyDetail: "",
  //   firstLogo: goCodeeLogoFirst,

  //   backgroundImage: goCodeeBackgroundImage,
  //   projects: ["Project1", "Project2", "Project3", "Project4", "Project5"],
  // },
];
